/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mark_com_boringssl_JNI */

#ifndef _Included_mark_com_boringssl_JNI
#define _Included_mark_com_boringssl_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mark_com_boringssl_JNI
 * Method:    stringFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_mark_com_boringssl_JNI_stringFromJni
  (JNIEnv *, jobject);

/*
 * Class:     mark_com_boringssl_JNI
 * Method:    connect
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_mark_com_boringssl_JNI_connect
  (JNIEnv *, jobject);

/*
 * Class:     mark_com_boringssl_JNI
 * Method:    serviceWebSockets
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_mark_com_boringssl_JNI_serviceWebSockets
  (JNIEnv *, jobject);

/*
 * Class:     mark_com_boringssl_JNI
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_mark_com_boringssl_JNI_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
