/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

/* Header for class mark_com_boringssl_JNI */

#ifndef _Included_mark_com_boringssl_JNI
#define _Included_mark_com_boringssl_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mark_com_boringssl_JNI
 * Method:    stringFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL JNI_stringFromJni
        (JNIEnv *, jobject);

/*
 * Class:     mark_com_boringssl_JNI
 * Method:    connect
 * Signature: ()V
 */
JNIEXPORT void JNICALL JNI_connect
        (JNIEnv *, jobject);

/*
 * Class:     mark_com_boringssl_JNI
 * Method:    serviceWebSockets
 * Signature: ()V
 */
JNIEXPORT void JNICALL JNI_serviceWebSockets
        (JNIEnv *, jobject);
#ifdef __cplusplus
}

static JNINativeMethod jni_native_methods[] = {
        {"stringFromJni",     "()Ljava/lang/String;", (void *) JNI_stringFromJni},
        {"connect",           "()V",                  (void *) JNI_connect},
        {"serviceWebSockets", "()V",                  (void *) JNI_serviceWebSockets}
};
#endif
#endif
