//
// Created by mark on 17-6-19.
//

#ifndef BORINGSSL_LIBWEBSOCKETS_WEBSOCKET_H
#define BORINGSSL_LIBWEBSOCKETS_WEBSOCKET_H
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "libwebsockets.h"
/* Header for class com_example_WebSocket */

#define BUFFER_SIZE 4096
/*
 * Class:     com_example_WebSocket
 * Method:    setAddress
 * Signature: (Ljava/lang/String;ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL jni_setAddress
  (JNIEnv *, jobject, jstring, jint, jstring);

/*
 * Class:     com_example_WebSocket
 * Method:    setUrl
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL jni_setUrl(JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_WebSocket
 * Method:    connect
 * Signature: ()V
 */
JNIEXPORT void JNICALL jni_connect
  (JNIEnv *, jobject);


static int callback( struct lws *wsi, enum lws_callback_reasons reason, void *user, void *in, size_t len );

#endif //BORINGSSL_LIBWEBSOCKETS_WEBSOCKET_H
